version: '3'
services:
    mysql:
      image: mysql:latest
      ports:
        - 3307:3306
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=appointments_helper
      volumes:
        - ./.volumes/mysql_data:/var/lib/mysql
        - ./.scripts/mysql/01_create_database.sql:/docker-entrypoint-initdb.d/init.sql